line-length = 79
exclude = [".venv/"]

[lint]
extend-select = [
    "I",
    "E",
    "W",
    "F",
    "C",
    "D101",
    "D102",
    "D103",
    "D104",
    "D201",
    "D202",
    "D204",
    "D205",
    "D209",
    "D417",
    "ERA",
]
preview = true

[lint.isort]
combine-as-imports = true
known-first-party = ["pixiv_bot"]
order-by-type = false

[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"
